// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIFDjQcWZVB5Tk22Tz6zoKe6YRnTjyHUQ',
    appId: '1:163923156878:web:7927b243096ca1deb48edf',
    messagingSenderId: '163923156878',
    projectId: 'p001-202eb',
    authDomain: 'p001-202eb.firebaseapp.com',
    storageBucket: 'p001-202eb.firebasestorage.app',
    measurementId: 'G-GM8SQJWF2Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu324YCWXCOxjqMBAfezcpJHj7Yo3ybUY',
    appId: '1:163923156878:android:8822600a933ed6e1b48edf',
    messagingSenderId: '163923156878',
    projectId: 'p001-202eb',
    storageBucket: 'p001-202eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCabISkOPhXZeFcXX1rJevqxNchuOvtY90',
    appId: '1:163923156878:ios:8d2493f733dd8f90b48edf',
    messagingSenderId: '163923156878',
    projectId: 'p001-202eb',
    storageBucket: 'p001-202eb.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCabISkOPhXZeFcXX1rJevqxNchuOvtY90',
    appId: '1:163923156878:ios:8d2493f733dd8f90b48edf',
    messagingSenderId: '163923156878',
    projectId: 'p001-202eb',
    storageBucket: 'p001-202eb.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );
}
